name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  dartlize:
    path: ../
  darto: ^0.0.10
  zard: ^0.0.3
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
