name: dartlize
description: Dartlize is a lightweight ORM for Dart designed to simplify database interactions inspired by the Sequelize ORM for Javascript.
version: 0.0.1
homepage: https://github.com/evandersondev/dartlize

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.7.5
  mysql1: ^0.20.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
