name: dartlize
description: Dartlize is discontinued. Please use [Dartonic](https://pub.dev/packages/dartonic) instead.
version: 0.0.2
homepage: https://github.com/evandersondev/dartlize

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.7.5
  mysql1: ^0.20.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
